#!/bin/bash
# Helper script to construct Railway public database URL
# Usage: ./scripts/get-railway-public-db-url.sh

echo "🔗 Railway Public Database Connection"
echo "======================================"
echo ""
echo "From Railway Dashboard, you should see:"
echo "  Host: ballast.proxy.rlwy.net"
echo "  Port: 32318"
echo ""
echo "To get the password, you can:"
echo ""
echo "Option 1: Get from Railway Dashboard"
echo "  1. Railway Dashboard → PostgreSQL service"
echo "  2. Go to 'Variables' tab"
echo "  3. Look for DATABASE_URL or PGPASSWORD"
echo "  4. Extract the password from the connection string"
echo ""
echo "Option 2: Use Railway CLI"
echo "  cd backend"
echo "  npx @railway/cli variables"
echo ""
echo "The connection string format should be:"
echo "  postgresql://postgres:PASSWORD@ballast.proxy.rlwy.net:32318/railway"
echo ""
echo "Once you have the password, run:"
echo "  cd backend"
echo "  export DATABASE_URL=\"postgresql://postgres:YOUR_PASSWORD@ballast.proxy.rlwy.net:32318/railway\""
echo "  npx ts-node scripts/create-admin-user.ts"
echo ""
