#!/bin/bash
# Guide script for setting up BLDCebu.com domain with Railway
# Usage: ./scripts/setup-domain-railway.sh

set -e

echo "🌐 Setting Up BLDCebu.com Domain with Railway"
echo "=============================================="
echo ""

echo "📋 Prerequisites:"
echo "   1. Railway account (sign up at https://railway.app)"
echo "   2. Domain registered: BLDCebu.com"
echo "   3. Access to domain DNS settings"
echo ""

echo "🚀 Step 1: Deploy to Railway"
echo "   -------------------------"
echo "   1. Install Railway CLI:"
echo "      npm i -g @railway/cli"
echo ""
echo "   2. Login to Railway:"
echo "      railway login"
echo ""
echo "   3. Deploy backend:"
echo "      cd backend"
echo "      railway init"
echo "      railway add postgresql"
echo "      railway up"
echo ""
echo "   4. Deploy frontend:"
echo "      cd frontend"
echo "      railway init"
echo "      railway variables set NEXT_PUBLIC_API_BASE_URL=https://[backend-url].railway.app"
echo "      railway up"
echo ""

echo "🌐 Step 2: Add Custom Domain in Railway"
echo "   ------------------------------------"
echo "   1. Go to Railway dashboard: https://railway.app/dashboard"
echo "   2. Select your frontend service"
echo "   3. Go to 'Settings' → 'Domains'"
echo "   4. Click 'Add Domain'"
echo "   5. Enter: BLDCebu.com"
echo "   6. Enter: www.BLDCebu.com"
echo "   7. Railway will show you DNS records to add"
echo ""

echo "📝 Step 3: Configure DNS at Your Domain Registrar"
echo "   ---------------------------------------------"
echo ""
echo "   Railway will provide DNS records. Typically:"
echo ""
echo "   For root domain (BLDCebu.com):"
echo "   Type: CNAME"
echo "   Name: @ (or blank)"
echo "   Value: [railway-provided-domain].railway.app"
echo ""
echo "   For www (www.BLDCebu.com):"
echo "   Type: CNAME"
echo "   Name: www"
echo "   Value: [railway-provided-domain].railway.app"
echo ""
echo "   ⚠️  If your registrar doesn't support CNAME for root domain:"
echo "   Type: A"
echo "   Name: @"
echo "   Value: [Railway IP - they'll provide this]"
echo ""

echo "⏳ Step 4: Wait for DNS Propagation"
echo "   --------------------------------"
echo "   - Usually takes 5-30 minutes"
echo "   - Can take up to 48 hours (rare)"
echo "   - Check status: https://dnschecker.org"
echo ""

echo "✅ Step 5: Verify"
echo "   -------------"
echo "   Once DNS propagates:"
echo "   - Visit: https://BLDCebu.com"
echo "   - Visit: https://www.BLDCebu.com"
echo "   - SSL certificate will be automatically provisioned"
echo ""

echo "💡 Tips:"
echo "   - Railway automatically provisions SSL certificates"
echo "   - Both root and www will work"
echo "   - You can add API subdomain later: api.BLDCebu.com"
echo ""

echo "📚 Need Help?"
echo "   - Railway Docs: https://docs.railway.app/guides/custom-domains"
echo "   - Check DNS: https://dnschecker.org"
echo ""
